### ISSUE TITLE
Some crash

### ISSUE THREAD

**Issue by Kevadro** [kegare/Cavern#2]
I got a crash creating any world (I want to play in 1.9.0 and i can't update to 1.9.4 because most of the mods aren't for this version):

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-beta-18.jar)
  LoadingPlugin (HardcoreDarkness-MC1.9-1.8.jar)
  SeasonsPreLoader (SeasonsAPI-1.1.3b.jar)
  BCModPlugin (zz-backpacks 1.9 - 3.0.10 beta.jar)
  LoadingPlugin (DimensionRules-MC1.9-1.0.jar)
  LoadingPluginBuildingBricks (BuildingBricks-1.9-2.0.2.jar)
  CXLibraryCore (cxlibrary-1.0.0.jar)
  FarseekCoreMod (Farseek-1.9-1.0.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 20/05/16 21:56
Description: Exception ticking world

java.lang.ArrayIndexOutOfBoundsException: 4
	at net.minecraft.world.biome.BiomeGenBase.func_76747_a(BiomeGenBase.java:169)
	at net.minecraft.world.gen.ChunkProviderOverworld.func_177458_a(ChunkProviderOverworld.java:514)
	at net.minecraft.world.gen.ChunkProviderServer.func_177458_a(ChunkProviderServer.java:319)
	at net.minecraft.world.WorldServer.func_175734_a(WorldServer.java:236)
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:125)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:196)
	at WorldServerOF.func_72835_b(WorldServerOF.java:37)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:694)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.world.biome.BiomeGenBase.func_76747_a(BiomeGenBase.java:169)
	at net.minecraft.world.gen.ChunkProviderOverworld.func_177458_a(ChunkProviderOverworld.java:514)
	at net.minecraft.world.gen.ChunkProviderServer.func_177458_a(ChunkProviderServer.java:319)
	at net.minecraft.world.WorldServer.func_175734_a(WorldServer.java:236)
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:125)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:196)
	at WorldServerOF.func_72835_b(WorldServerOF.java:37)

-- Affected level --
Details:
	Level name: Test Mods 1
	All players: 1 total; [EntityPlayerMP['Kevadro'/1178, l='Test Mods 1', x=236,50, y=68,00, z=248,50]]
	Chunk stats: ServerChunkCache: 627 Drop: 338
	Level seed: -5583174223429974410
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {"diamondSize":8,"lapisCenterHeight":16,"lavaLakeChance":80,"redstoneMaxHeight":16,"diamondMaxHeight":16,"coalMaxHeight":128,"coalMinHeight":0,"seaLevel":63,"graniteCount":10,"riverSize":4,"gravelMinHeight":0,"graniteSize":33,"redstoneSize":8,"fixedBiome":-1,"waterLakeChance":4,"dioriteMinHeight":0,"andesiteCount":10,"graniteMaxHeight":80,"redstoneMinHeight":0,"lapisSize":7,"dirtCount":10,"ironMinHeight":0,"dioriteMaxHeight":80,"coalCount":20,"gravelCount":8,"coalSize":17,"gravelSize":33,"ironMaxHeight":64,"lapisSpread":16,"dioriteCount":10,"andesiteSize":33,"biomeSize":4,"graniteMinHeight":0,"goldCount":2,"diamondCount":1,"dirtSize":33,"gravelMaxHeight":256,"goldSize":9,"ironCount":20,"diamondMinHeight":0,"ironSize":9,"redstoneCount":8,"andesiteMinHeight":0,"dioriteSize":33,"goldMaxHeight":32,"dungeonChance":8,"andesiteMaxHeight":80,"dirtMinHeight":0,"lapisCount":1,"goldMinHeight":0,"dirtMaxHeight":256,"lowerLimitScale":512.0,"biomeDepthOffset":0.0,"upperLimitScale":512.0,"heightScale":684.412,"biomeScaleWeight":1.0,"biomeDepthWeight":1.0,"mainNoiseScaleZ":80.0,"mainNoiseScaleY":160.0,"depthNoiseScaleX":200.0,"mainNoiseScaleX":80.0,"baseSize":8.5,"depthNoiseScaleZ":200.0,"stretchY":12.0,"depthNoiseScaleExponent":0.5,"biomeScaleOffset":0.0,"coordinateScale":684.412,"useStrongholds":true,"useMineShafts":true,"useTemples":true,"useLavaOceans":false,"useCaves":true,"useWaterLakes":true,"useLavaLakes":true,"useMonuments":true,"useRavines":true,"useDungeons":true,"useVillages":true}
	Level spawn location: World: (244,64,256), Chunk: (at 4,4,0 in 15,16; contains blocks 240,0,256 to 255,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 133 game time, 19149 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 15689 (now: false), thunder time: 160372 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:694)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1106576304 bytes (1055 MB) / 2570715136 bytes (2451 MB) up to 2570715136 bytes (2451 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2554M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1G
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.23 Powered by Forge 12.16.1.1907 Optifine OptiFine_1.9_HD_U_B3 50 mods loaded, 50 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.1.1907.jar) 
	UCHIJAAAA	Forge{12.16.1.1907} [Minecraft Forge] (forge-1.9-12.16.1.1907.jar) 
	UCHIJAAAA	buildingbrickshooks{1.9-2.0.2} [Building Bricks Hooks] (minecraft.jar) 
	UCHIJAAAA	backpacks16840{3.0.10} [Backpacks!] (zz-backpacks 1.9 - 3.0.10 beta.jar) 
	UCHIJAAAA	JEI{3.3.3.197} [Just Enough Items] (jei_1.9-3.3.3.197.jar) 
	UCHIJAAAA	abyssalcraft{1.9.1.6} [AbyssalCraft] (AbyssalCraft-1.9-1.9.1.6.jar) 
	UCHIJAAAA	armorplus{1.12.2-1.9} [ArmorPlus] (ArmorPlus1.12.2(1.9).jar) 
	UCHIJAAAA	basemetals{2.2.1} [Base Metals] (BaseMetals_1.9-2.2.1.jar) 
	UCHIJAAAA	BetterAchievements{0.2.5.19} [Better Achievements] (BetterAchievements-1.9-0.2.5.19.jar) 
	UCHIJAAAA	BBG{4.0.0} [BetterBedrockGen] (BetterBedrockGenerator-1.9.0-3.0.0.jar) 
	UCHIJAAAA	blockdrops{1.0.0} [Block Drops] (Block Drops-1.9-1.0.0.jar) 
	UCHIJAAAA	bookshelf{1.2.0.226} [Bookshelf] (Bookshelf-1.9-1.2.0.237.jar) 
	UCHIJAAAA	Quark{beta-18} [Quark] (Quark-beta-18.jar) 
	UCHIJAAAA	buildingbricks{1.9-2.0.2} [buildingbricks] (BuildingBricks-1.9-2.0.2.jar) 
	UCHIJAAAA	cavern{1.0.2} [Cavern] (Cavern_1.9-v1.0.2.jar) 
	UCHIJAAAA	customcrosshairmod{0.5-forge} [Custom Crosshair Mod] (crosshairmod-v0.5-forge-mc1.9.jar) 
	UCHIJAAAA	CustomBackgrounds{1.0} [Custom Backgrounds] (CustomBackgrounds-MC1.9-1.1.jar) 
	UCHIJAAAA	customnpcs{1.9.0_beta} [CustomNPCs] (CustomNPCs_1.9.0_beta(20may16).jar) 
	UCHIJAAAA	cxlibrary{1.0.0} [CXLibrary] (cxlibrary-1.0.0.jar) 
	UCHIJAAAA	DarkUtils{1.1.0.34} [Dark Utilities] (DarkUtilities-1.9-1.1.0.34.jar) 
	UCHIJAAAA	DimensionRules{1.0} [Dimension Rules] (DimensionRules-MC1.9-1.0.jar) 
	UCHIJAAAA	elementsofpower{0.7.7-alpha} [Elements of Power] (ElementsOfPower-1.9-0.7.7-alpha.jar) 
	UCHIJAAAA	EnhancedTools{1.9-1.0.0} [EnhancedTools] (Enhanced Tools 1.9-1.0.0.jar) 
	UCHIJAAAA	excore{1.5.3} [EXCore] (Excore-1.5.3-1.9.jar) 
	UCHIJAAAA	golems{4.02} [Extra Golems] (ExtraGolems[1.9]-4.02 (1).jar) 
	UCHIJAAAA	EzTimeKeeper{2.1.3} [Time Keeper] (eztimekeeper-2.1.3.jar) 
	UCHIJAAAA	Farseek{1.9-1.0} [Farseek] (Farseek-1.9-1.0.jar) 
	UCHIJAAAA	FEI{1.0.10} [Forever Enough Items] (ForeverEnoughItems-1.0.10-1.9.jar) 
	UCHIJAAAA	grapple_hooks{1.0.5} [Grapple Hooks] (Grapple Hooks-1.9-1.0.5.jar) 
	UCHIJAAAA	gravestone{1.2.4} [Gravestone] (Gravestone Mod 1.2.4 .jar) 
	UCHIJAAAA	HardcoreDarkness{1.8} [Hardcore Darkness] (HardcoreDarkness-MC1.9-1.8.jar) 
	UCHIJAAAA	InfernalMobs{1.6.9} [Infernal Mobs] (InfernalMobs-1.9.jar) 
	UCHIJAAAA	IronChest{6.0.133.777} [Iron Chest] (ironchest-1.9-6.0.133.777.jar) 
	UCHIJAAAA	journeymap{1.9-5.2.0b1} [JourneyMap] (journeymap-1.9-5.2.0b1-unlimited.jar) 
	UCHIJAAAA	jeresources{0.4.3} [Just Enough Resources] (JustEnoughResources-1.9-0.4.3.jar) 
	UCHIJAAAA	kk{0.7.7} [Kingdom Keys Re:Coded] (Kingdom Keys Re Coded-1.9-0.7.7-19-universal.jar) 
	UCHIJAAAA	mantle{1.9-0.9.4.jenkins114} [Mantle] (Mantle-1.9-0.9.4.jar) 
	UCHIJAAAA	mineralogy{3.0.0} [Mineralogy] (Mineralogy_1.9.0-3.0.0.jar) 
	UCHIJAAAA	modernmetals{0.9.2.3} [Modern Metals] (ModernMetals-0.9.2.3.jar) 
	UCHIJAAAA	MoreFurnaces{1.6.0} [More Furnaces] (MoreFurnaces-1.6.0-MC1.9.jar) 
	UCHIJAAAA	nethermetals{1.0.4} [Nether Metals] (NetherMetals-1.0.4.jar) 
	UCHIJAAAA	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.9-3.0.6.jar) 
	UCHIJAAAA	recipehandler{0.4} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.4(1.9).jar) 
	UCHIJAAAA	NoPotionShift{1.0.0} [No Potion Shift] (nopotionshift_1.9-1.0.0.jar) 
	UCHIJAAAA	xreliquary{1.9-1.3.1.322} [Reliquary] (Reliquary-1.9-1.3.1.322.jar) 
	UCHIJAAAA	seasonsapi{1.1.3b} [Seasons API] (SeasonsAPI-1.1.3b.jar) 
	UCHIJAAAA	SimpleDimensions{1.3} [Simple Dimensions] (SimpleDimensions-MC1.9-1.3.jar) 
	UCHIJAAAA	soundfilters{0.9_for_1.9} [Sound Filters] (SoundFilters-0.9_for_1.9.jar) 
	UCHIJAAAA	ultimate_unicorn_mod{1.4.12} [Wings, Horns, and Hooves, the Ultimate Unicorn Mod!] (ultimate_unicorn_mod-1.9-1.4.12.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-beta-18.jar)
  vazkii.quark.base.asm.ClassTransformer
LoadingPlugin (HardcoreDarkness-MC1.9-1.8.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
SeasonsPreLoader (SeasonsAPI-1.1.3b.jar)
  mod.mindcraft.seasons.asm.Transformer
BCModPlugin (zz-backpacks 1.9 - 3.0.10 beta.jar)
  brad16840.common.asm.ClassTransformer
LoadingPlugin (DimensionRules-MC1.9-1.0.jar)
  lumien.dimensionrules.asm.ClassTransformer
LoadingPluginBuildingBricks (BuildingBricks-1.9-2.0.2.jar)
  com.hea3ven.buildingbricks.core.load.ClassTransformerBuildingBricks
CXLibraryCore (cxlibrary-1.0.0.jar)
  cubex2.cxlibrary.CoreModTransformer
FarseekCoreMod (Farseek-1.9-1.0.jar)
  farseek.core.FarseekClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Kevadro'/1178, l='Test Mods 1', x=236,50, y=68,00, z=248,50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.9_HD_U_B3
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 365.19
	OpenGlRenderer: GeForce 710M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by Kevadro** [comment]
This is duplicated, sorry, I close it
