### ISSUE TITLE
[1.9.4] Crash with biomes of plenty

### ISSUE THREAD

**Issue by Kazzamkablam** [kegare/Cavern#3]
I tried to enter world and this happened:
(Cavern_1.9.4-v1.0.7.jar)

Log: http://www.filedropper.com/fml-client-latest_3

I did change configs but that didn't do anything.

Time: 6/5/16 5:12 PM
Description: Ticking memory connection

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class biomesoplenty.common.block.BlockBOPGrass$BOPGrassType, values=[spectral_moss, smoldering, loamy, sandy, silty, origin, overgrown_netherrack, daisy]} as it does not exist in BlockStateContainer{block=biomesoplenty:dirt, properties=[coarse, variant]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:197)
	at biomesoplenty.common.block.BlockBOPGrass.canSustainPlantType(BlockBOPGrass.java:125)
	at biomesoplenty.common.block.BlockBOPGrass.canSustainPlant(BlockBOPGrass.java:166)
	at cavern.block.BlockAcresia.func_180671_f(BlockAcresia.java:98)
	at cavern.world.gen.WorldGenAcresia.func_180709_b(WorldGenAcresia.java:39)
	at cavern.world.ChunkProviderCaveland.func_185931_b(ChunkProviderCaveland.java:223)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1005)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:988)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.world.World.func_72964_e(World.java:301)
	at atomicstryker.ruins.common.RuinsMod.onEntityEnteringChunk(RuinsMod.java:132)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_537_RuinsMod_onEntityEnteringChunk_EnteringChunk.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.world.chunk.Chunk.func_76612_a(Chunk.java:723)
	at net.minecraft.world.World.func_72838_d(World.java:1124)
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1062)
	at net.minecraft.server.management.PlayerList.func_72377_c(PlayerList.java:368)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:163)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:240)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:53)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:189)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:730)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
	at java.lang.Thread.run(Unknown Source)

**Comment by kegare** [comment]
Thanks!
Fixed on 1.0.8 build.
