### ISSUE TITLE
Crash on startup with latest Forge (2387)

### ISSUE THREAD

**Issue by Zarepheth** [kegare/Cavern#31]
Yes, I know that from the change log for this version, it ought to run on Forge 2387 without error - however, it is crashing for me - during model registration.

Minecraft 1.12
Forge 14.21.1.2387
Cavern 1.8.4

```
[20:34:19] [main/INFO] [FML]: Applying holder lookups
[20:34:19] [main/INFO] [FML]: Holder lookups applied
[20:34:19] [main/ERROR] [FML]: Exception caught during firing event net.minecraftforge.client.event.ModelRegistryEvent@17bb8d29:
java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/registry/RegistryDelegate
	at net.minecraft.client.renderer.block.model.ModelBakery.registerItemVariants(ModelBakery.java:1081) ~[cfz.class:?]
	at net.minecraftforge.client.model.ModelLoader.setCustomModelResourceLocation(ModelLoader.java:1126) ~[ModelLoader.class:?]
	at cavern.item.CaveItems.registerModel(CaveItems.java:164) ~[CaveItems.class:?]
	at cavern.block.CaveBlocks.registerModel(CaveBlocks.java:124) ~[CaveBlocks.class:?]
	at cavern.block.CaveBlocks.registerModels(CaveBlocks.java:107) ~[CaveBlocks.class:?]
	at cavern.core.Cavern.registerModels(Cavern.java:140) ~[Cavern.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_9_Cavern_registerModels_ModelRegistryEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	...
```

[Log File on paste.ee](https://paste.ee/p/jAYwk)

**Comment by Zarepheth** [comment]
The problem might be with Optifine rather than your mod. It looks like Optifine is intercepting model registration.
Suspect frame in stack trace:
```
at ...
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_9_Cavern_registerModels_ModelRegistryEvent.invoke(.dynamic) ~[?:?]
at ...
```

**Comment by kegare** [comment]
Yes, OptiFine is not supported yet.
_OptiFine 1.12_HD_U_C3 : Compatible with Forge 2331_
You should wait for a moment.
