### ISSUE TITLE
1.10-v1.0.9 Crashes on server start

### ISSUE THREAD

**Issue by darkphan** [kegare/Cavern#7]
Seems the mod tries to access a sound classs not available on servers:

```
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/audio/ISound
        at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
        at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:596)
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/audio/ISound
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
        at java.lang.Class.getConstructor0(Class.java:3075)
        at java.lang.Class.newInstance(Class.java:412)
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.instantiate(SimpleNetworkWrapper.java:166)
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.registerMessage(SimpleNetworkWrapper.java:159)
        at cavern.network.CaveNetworkRegistry.registerMessage(CaveNetworkRegistry.java:27)
        at cavern.network.CaveNetworkRegistry.registerMessages(CaveNetworkRegistry.java:81)
        at cavern.core.Cavern.preInit(Cavern.java:95)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:577)
        at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:235)
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:213)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
        at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:593)
        ... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.audio.ISound
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 40 more
Caused by: java.lang.NullPointerException
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
        ... 42 more

```

**Comment by darkphan** [comment]
oops, someone else already opened an issue on this.
